services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test"]
      interval: 5s
      timeout: 5s
      retries: 5

  reply-core:
    image: stllorg/reply-core
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/test
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - MP_JWT_VERIFY_PUBLICKEY_LOCATION=/run/secrets/public_key_secret
      - SMALLRYE_JWT_SIGN_KEY_LOCATION=/run/secrets/private_key_secret
    secrets:
      - public_key_secret
      - private_key_secret
    depends_on:
      - db

secrets:
  public_key_secret:
    file: ./jwt/publicKey.pem
  private_key_secret:
    file: ./jwt/privateKey.pem

volumes:
  postgres_data: